<script setup lang="ts">
import { Head, Link, router } from '@inertiajs/vue3';
import AppLayout from '@/Layouts/AppLayout.vue';
import { computed } from 'vue';

interface PlanItem {
    id: number;
    action: string;
    owner_type: 'human' | 'agent';
    agent_slug: string | null;
    priority: string;
    due_day: string | null;
    status: string;
    is_overdue: boolean;
}

interface Plan {
    id: number;
    week_starting: string;
    week_label: string;
    is_current_week: boolean;
    status: string;
    focus_areas: string[];
    targets: Record<string, number>;
    progress_percent: number;
    items_count: number;
    completed_count: number;
    agent_items_count: number;
    human_items_count: number;
    goal_name: string | null;
}

interface CurrentPlan {
    id: number;
    week_label: string;
    status: string;
    focus_areas: string[];
    targets: Record<string, number>;
    progress_percent: number;
    strategy_notes: string | null;
    items: PlanItem[];
}

interface Agent {
    id: number;
    name: string;
    slug: string;
}

const props = defineProps<{
    plans: Plan[];
    currentPlan: CurrentPlan | null;
    activeGoal: { id: number; name: string; progress_percent: number } | null;
    availableAgents: Agent[];
}>();

const getStatusBadge = (status: string) => {
    const badges: Record<string, { class: string; text: string }> = {
        draft: { class: 'bg-zinc-500/20 text-zinc-400', text: 'Draft' },
        approved: { class: 'bg-blue-500/20 text-blue-400', text: 'Approved' },
        active: { class: 'bg-emerald-500/20 text-emerald-400', text: 'Active' },
        completed: { class: 'bg-purple-500/20 text-purple-400', text: 'Completed' },
        rejected: { class: 'bg-red-500/20 text-red-400', text: 'Rejected' },
        revision_requested: { class: 'bg-amber-500/20 text-amber-400', text: 'Revising' },
    };
    return badges[status] || badges.draft;
};

const getPriorityBadge = (priority: string) => {
    const badges: Record<string, string> = {
        critical: 'bg-red-500/20 text-red-400',
        high: 'bg-orange-500/20 text-orange-400',
        medium: 'bg-blue-500/20 text-blue-400',
        low: 'bg-zinc-500/20 text-zinc-400',
    };
    return badges[priority] || badges.medium;
};

const getItemStatusBadge = (status: string, isOverdue: boolean) => {
    if (isOverdue) return { class: 'bg-red-500/20 text-red-400', text: 'Overdue' };
    const badges: Record<string, { class: string; text: string }> = {
        pending: { class: 'bg-zinc-500/20 text-zinc-400', text: 'Pending' },
        in_progress: { class: 'bg-blue-500/20 text-blue-400', text: 'In Progress' },
        completed: { class: 'bg-emerald-500/20 text-emerald-400', text: 'Done' },
        skipped: { class: 'bg-amber-500/20 text-amber-400', text: 'Skipped' },
    };
    return badges[status] || badges.pending;
};

const focusAreaLabels: Record<string, string> = {
    lead_gen: '🎯 Lead Gen',
    closing: '🤝 Closing',
    upsells: '📈 Upsells',
    retention: '💚 Retention',
    operations: '⚙️ Operations',
    content: '✍️ Content',
};

const getFocusLabel = (area: string) => focusAreaLabels[area] || area;

const formatTarget = (key: string, value: number) => {
    if (key === 'revenue' || key === 'pipeline') {
        return '$' + value.toLocaleString();
    }
    return value.toString();
};

const updateItemStatus = (itemId: number, status: string) => {
    router.patch(`/weekly-plans/items/${itemId}`, { status }, {
        preserveScroll: true,
    });
};
</script>

<template>
    <AppLayout>
        <Head title="Weekly Plans" />

        <div class="p-6 space-y-6">
            <!-- Header -->
            <div class="flex items-center justify-between">
                <div>
                    <h1 class="text-2xl font-semibold text-[var(--color-text-primary)]">Weekly Plans</h1>
                    <p class="text-[var(--color-text-tertiary)] text-sm mt-1">Strategic action plans generated by Business Strategist</p>
                </div>
                <div class="flex items-center gap-3">
                    <Link
                        v-if="activeGoal"
                        :href="`/goals/${activeGoal.id}`"
                        class="text-[var(--color-text-tertiary)] hover:text-[var(--color-text-primary)] text-sm"
                    >
                        Goal: {{ activeGoal.name }} ({{ activeGoal.progress_percent.toFixed(0) }}%)
                    </Link>
                </div>
            </div>

            <!-- Current Week Plan -->
            <div v-if="currentPlan" class="hero-gradient border border-[var(--color-border-subtle)] rounded-xl shadow-sm relative overflow-hidden">
                <!-- Decorative background accent -->
                <div class="absolute top-0 right-0 w-64 h-64 bg-blue-400/5 rounded-full blur-3xl -mr-32 -mt-32 pointer-events-none"></div>
                <div class="p-6 relative">
                    <div class="flex items-start justify-between mb-6">
                        <div>
                            <div class="text-xs font-medium text-[var(--color-text-tertiary)] uppercase tracking-wider mb-1">This Week</div>
                            <h2 class="text-xl font-semibold text-[var(--color-text-primary)]">{{ currentPlan.week_label }}</h2>
                        </div>
                        <span :class="[getStatusBadge(currentPlan.status).class, 'px-3 py-1 rounded-full text-xs font-medium']">
                            {{ getStatusBadge(currentPlan.status).text }}
                        </span>
                    </div>

                    <!-- Focus Areas & Targets -->
                    <div class="grid grid-cols-1 md:grid-cols-2 gap-6 mb-6">
                        <div>
                            <div class="text-xs font-medium text-[var(--color-text-tertiary)] uppercase tracking-wider mb-2">Focus Areas</div>
                            <div class="flex flex-wrap gap-2">
                                <span
                                    v-for="area in currentPlan.focus_areas"
                                    :key="area"
                                    class="px-2.5 py-1 bg-[var(--color-bg-tertiary)] rounded-md text-sm text-[var(--color-text-secondary)]"
                                >
                                    {{ getFocusLabel(area) }}
                                </span>
                            </div>
                        </div>
                        <div>
                            <div class="text-xs font-medium text-[var(--color-text-tertiary)] uppercase tracking-wider mb-2">Targets</div>
                            <div class="flex flex-wrap gap-4">
                                <div v-for="(value, key) in currentPlan.targets" :key="key" class="text-sm">
                                    <span class="text-[var(--color-text-tertiary)] capitalize">{{ key }}:</span>
                                    <span class="text-[var(--color-text-primary)] ml-1 font-medium">{{ formatTarget(key as string, value) }}</span>
                                </div>
                            </div>
                        </div>
                    </div>

                    <!-- Progress -->
                    <div class="mb-6">
                        <div class="flex items-center justify-between text-sm mb-2">
                            <span class="text-[var(--color-text-tertiary)]">Progress</span>
                            <span class="text-[var(--color-text-primary)] font-medium">{{ currentPlan.progress_percent.toFixed(0) }}%</span>
                        </div>
                        <div class="h-2.5 bg-[var(--color-bg-tertiary)] rounded-full overflow-hidden">
                            <div
                                :class="[currentPlan.progress_percent >= 100 ? 'bg-emerald-500' : 'bg-blue-500', 'h-full rounded-full transition-all duration-500']"
                                :style="{ width: `${currentPlan.progress_percent}%` }"
                            ></div>
                        </div>
                    </div>

                    <!-- Action Items -->
                    <div class="space-y-2">
                        <div class="text-xs font-medium text-[var(--color-text-tertiary)] uppercase tracking-wider mb-3">Action Items</div>
                        <div
                            v-for="item in currentPlan.items.slice(0, 5)"
                            :key="item.id"
                            class="flex items-center justify-between p-3 bg-[var(--color-bg-tertiary)] rounded-lg border border-[var(--color-border-subtle)]"
                        >
                            <div class="flex items-center gap-3">
                                <button
                                    v-if="item.status !== 'completed'"
                                    @click="updateItemStatus(item.id, 'completed')"
                                    class="w-5 h-5 border border-[var(--color-border-default)] rounded hover:border-emerald-500 hover:bg-emerald-500/20 transition-colors"
                                ></button>
                                <div v-else class="w-5 h-5 bg-emerald-500 rounded flex items-center justify-center">
                                    <svg class="w-3 h-3 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="3" d="M5 13l4 4L19 7" />
                                    </svg>
                                </div>
                                <div>
                                    <span :class="item.status === 'completed' ? 'text-[var(--color-text-tertiary)] line-through' : 'text-[var(--color-text-primary)]'">
                                        {{ item.action }}
                                    </span>
                                    <span
                                        v-if="item.owner_type === 'agent'"
                                        class="ml-2 text-xs text-purple-500"
                                    >
                                        {{ item.agent_slug }}
                                    </span>
                                </div>
                            </div>
                            <div class="flex items-center gap-2">
                                <span :class="[getPriorityBadge(item.priority), 'px-2 py-0.5 rounded text-xs']">
                                    {{ item.priority }}
                                </span>
                                <span :class="[getItemStatusBadge(item.status, item.is_overdue).class, 'px-2 py-0.5 rounded text-xs']">
                                    {{ getItemStatusBadge(item.status, item.is_overdue).text }}
                                </span>
                            </div>
                        </div>
                        <div v-if="currentPlan.items.length > 5" class="text-center pt-2">
                            <Link
                                :href="`/weekly-plans/${currentPlan.id}`"
                                class="text-blue-500 hover:text-blue-400 text-sm"
                            >
                                View all {{ currentPlan.items.length }} items
                            </Link>
                        </div>
                    </div>
                </div>

                <div class="border-t border-[var(--color-border-subtle)] px-6 py-4 flex justify-end relative">
                    <Link
                        :href="`/weekly-plans/${currentPlan.id}`"
                        class="text-blue-500 hover:text-blue-400 text-sm font-medium transition-colors"
                    >
                        View Full Plan →
                    </Link>
                </div>
            </div>

            <!-- No Current Plan -->
            <div v-else class="card p-8 text-center">
                <div class="text-4xl mb-3">📋</div>
                <h3 class="text-lg font-medium text-[var(--color-text-primary)] mb-2">No Plan for This Week</h3>
                <p class="text-[var(--color-text-tertiary)] text-sm mb-4">
                    The Business Strategist agent creates weekly plans on Monday mornings.
                </p>
                <div class="text-xs text-[var(--color-text-tertiary)]">
                    Next planning run: Monday 6:00 AM
                </div>
            </div>

            <!-- Past Plans -->
            <div class="card">
                <div class="border-b border-[var(--color-border-default)] px-6 py-4">
                    <h2 class="text-lg font-medium text-[var(--color-text-primary)]">Plan History</h2>
                </div>

                <div v-if="plans.length" class="divide-y divide-[var(--color-border-default)]">
                    <Link
                        v-for="plan in plans"
                        :key="plan.id"
                        :href="`/weekly-plans/${plan.id}`"
                        class="block px-6 py-4 hover:bg-[var(--color-bg-tertiary)] transition-colors"
                    >
                        <div class="flex items-center justify-between">
                            <div class="flex items-center gap-4">
                                <div class="w-12 h-12 bg-[var(--color-bg-tertiary)] rounded-lg flex items-center justify-center">
                                    <span v-if="plan.is_current_week" class="text-blue-400 text-xl">📍</span>
                                    <span v-else class="text-[var(--color-text-tertiary)] text-xl">📋</span>
                                </div>
                                <div>
                                    <div class="flex items-center gap-2">
                                        <span class="text-[var(--color-text-primary)] font-medium">{{ plan.week_label }}</span>
                                        <span
                                            v-if="plan.is_current_week"
                                            class="px-2 py-0.5 bg-blue-500/20 text-blue-400 rounded text-xs"
                                        >
                                            Current
                                        </span>
                                    </div>
                                    <div class="text-[var(--color-text-tertiary)] text-sm flex items-center gap-3">
                                        <span>{{ plan.completed_count }}/{{ plan.items_count }} items</span>
                                        <span v-if="plan.focus_areas.length">
                                            {{ plan.focus_areas.map(a => getFocusLabel(a)).join(', ') }}
                                        </span>
                                    </div>
                                </div>
                            </div>
                            <div class="flex items-center gap-4">
                                <div class="w-24">
                                    <div class="h-1.5 bg-[var(--color-bg-elevated)] rounded-full overflow-hidden">
                                        <div
                                            :class="plan.progress_percent >= 100 ? 'bg-emerald-500' : 'bg-blue-500'"
                                            class="h-full rounded-full"
                                            :style="{ width: `${plan.progress_percent}%` }"
                                        ></div>
                                    </div>
                                </div>
                                <span :class="[getStatusBadge(plan.status).class, 'px-2 py-1 rounded text-xs font-medium w-20 text-center']">
                                    {{ getStatusBadge(plan.status).text }}
                                </span>
                            </div>
                        </div>
                    </Link>
                </div>

                <div v-else class="px-6 py-12 text-center">
                    <p class="text-[var(--color-text-tertiary)]">No plans yet. The Business Strategist will create the first plan on Monday.</p>
                </div>
            </div>
        </div>
    </AppLayout>
</template>

<style scoped>
.hero-gradient {
    background: linear-gradient(to bottom right, 
        var(--color-bg-tertiary), 
        var(--color-bg-secondary), 
        var(--color-bg-secondary)
    );
}

.light .hero-gradient {
    background: linear-gradient(to bottom right, 
        rgb(239 246 255), 
        white, 
        white
    );
}
</style>
