{{-- IRS Form 1040-ES — Estimated Tax Payment Voucher --}}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <script src="https://cdn.tailwindcss.com"></script>
    <style>
        @page { size: letter; margin: 0; }
        body { font-family: 'Courier New', monospace; }
    </style>
</head>
<body class="bg-white">
    {{-- Cover Letter / Instructions --}}
    <div class="p-12">
        <div class="border-b-2 border-blue-600 pb-4 mb-8">
            <h1 class="text-2xl font-bold text-gray-900">Estimated Tax Payment — Q{{ $quarter }} {{ $year }}</h1>
            <p class="text-gray-600 mt-1">Prepared for {{ $profile->spouse_name ? $profile->spouse_name.' & ' : '' }}{{ $profile->user->name ?? 'Taxpayer' }}</p>
        </div>

        <div class="bg-blue-50 border border-blue-200 rounded-lg p-6 mb-8">
            <div class="text-center">
                <div class="text-sm text-blue-600 font-semibold uppercase tracking-wide">Amount Due</div>
                <div class="text-4xl font-bold text-blue-700 mt-1">${{ number_format($payment_amount, 2) }}</div>
                <div class="text-sm text-blue-600 mt-2">Due by {{ $due_date }}</div>
            </div>
        </div>

        <h2 class="text-lg font-bold text-gray-800 mb-4">How to Pay</h2>

        {{-- Option 1: EFTPS --}}
        <div class="mb-6">
            <h3 class="font-bold text-gray-700 mb-2">Option 1: EFTPS (Recommended)</h3>
            <div class="bg-gray-50 rounded-lg p-4">
                <p class="text-sm text-gray-600 mb-2">{{ $payment_instructions['online']['url'] }}</p>
                <ol class="list-decimal list-inside text-sm text-gray-700 space-y-1">
                    @foreach($payment_instructions['online']['steps'] as $step)
                        <li>{{ $step }}</li>
                    @endforeach
                </ol>
            </div>
        </div>

        {{-- Option 2: Direct Pay --}}
        <div class="mb-6">
            <h3 class="font-bold text-gray-700 mb-2">Option 2: IRS Direct Pay</h3>
            <div class="bg-gray-50 rounded-lg p-4">
                <p class="text-sm text-gray-600 mb-2">{{ $payment_instructions['alternative']['url'] }}</p>
                <ol class="list-decimal list-inside text-sm text-gray-700 space-y-1">
                    @foreach($payment_instructions['alternative']['steps'] as $step)
                        <li>{{ $step }}</li>
                    @endforeach
                </ol>
            </div>
        </div>

        {{-- Option 3: Mail --}}
        <div class="mb-6">
            <h3 class="font-bold text-gray-700 mb-2">Option 3: Mail with Voucher Below</h3>
            <div class="bg-gray-50 rounded-lg p-4">
                <p class="text-sm text-gray-700">{{ $payment_instructions['mail']['note'] }}</p>
                <p class="text-sm text-gray-600 mt-2 whitespace-pre-line">{{ $payment_instructions['mail']['address'] }}</p>
            </div>
        </div>

        <div class="text-xs text-gray-400 mt-8 border-t pt-4">
            Generated by Zao Dash Tax Office — {{ now()->format('F j, Y g:i A') }}
        </div>
    </div>

    {{-- Payment Voucher (for mailing) --}}
    <div class="break-before-page p-12">
        <div class="border-2 border-black p-8 max-w-xl mx-auto" style="font-family: 'Courier New', monospace;">
            <div class="text-center border-b border-black pb-2 mb-4">
                <div class="text-xs">Form</div>
                <div class="text-2xl font-bold">1040-ES</div>
                <div class="text-xs">Department of the Treasury</div>
                <div class="text-xs">Internal Revenue Service</div>
                <div class="text-xs mt-1">{{ $year }} Estimated Tax Payment Voucher {{ $quarter }}</div>
            </div>

            <div class="text-xs space-y-3">
                <div class="flex justify-between border-b border-gray-300 pb-1">
                    <span>Calendar year — Due {{ $due_date }}</span>
                    <span>OMB No. 1545-0074</span>
                </div>

                <div>
                    <div class="text-xs text-gray-500">Print name(s) shown on return</div>
                    <div class="font-bold text-sm border-b border-gray-300 py-1">
                        {{ strtoupper($profile->user->name ?? '') }}
                        @if($profile->spouse_name)
                            & {{ strtoupper($profile->spouse_name) }}
                        @endif
                    </div>
                </div>

                <div>
                    <div class="text-xs text-gray-500">Address</div>
                    <div class="border-b border-gray-300 py-1">
                        {{ strtoupper($profile->address ?? '') }}
                    </div>
                </div>

                <div>
                    <div class="text-xs text-gray-500">City, state, and ZIP code</div>
                    <div class="border-b border-gray-300 py-1">
                        {{ strtoupper(($profile->city ?? '').', '.($profile->state ?? '').' '.($profile->zip ?? '')) }}
                    </div>
                </div>

                <div class="flex justify-between items-center border-2 border-black p-3 bg-gray-50">
                    <div>
                        <div class="text-xs text-gray-500">Amount of estimated tax you are paying</div>
                        <div class="text-xs text-gray-500">by check or money order</div>
                    </div>
                    <div class="text-xl font-bold">${{ number_format($payment_amount, 2) }}</div>
                </div>
            </div>
        </div>

        <div class="text-center mt-4 text-xs text-gray-400">
            ✂ Cut along dotted line — Mail voucher with payment
        </div>
    </div>
</body>
</html>
