{{-- IRS Form 1096 — Annual Summary and Transmittal --}}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <script src="https://cdn.tailwindcss.com"></script>
    <style>
        @page { size: letter; margin: 0; }
        body { font-family: 'Courier New', monospace; }
    </style>
</head>
<body class="bg-white">
    <div class="p-12">
        <div class="border-2 border-black p-8 max-w-2xl mx-auto">
            <div class="text-center border-b-2 border-black pb-4 mb-6">
                <div class="text-xs">Form</div>
                <div class="text-3xl font-bold">1096</div>
                <div class="text-sm font-bold">Annual Summary and Transmittal of</div>
                <div class="text-sm font-bold">U.S. Information Returns</div>
                <div class="text-xs text-gray-600 mt-1">Department of the Treasury — Internal Revenue Service</div>
                <div class="text-lg font-bold mt-2">{{ $year }}</div>
            </div>

            <div class="space-y-4 text-sm">
                <div>
                    <div class="text-xs text-gray-500 uppercase">Filer's name</div>
                    <div class="font-bold border-b border-gray-300 py-1">
                        {{ strtoupper($profile->entity_name ?? 'ZAO WEB DESIGN, LLC') }}
                    </div>
                </div>

                <div>
                    <div class="text-xs text-gray-500 uppercase">Street address</div>
                    <div class="border-b border-gray-300 py-1">
                        {{ strtoupper($profile->entity_address ?? $profile->address ?? '') }}
                    </div>
                </div>

                <div>
                    <div class="text-xs text-gray-500 uppercase">City, state, and ZIP code</div>
                    <div class="border-b border-gray-300 py-1">
                        {{ strtoupper(($profile->city ?? '').', '.($profile->state ?? '').' '.($profile->zip ?? '')) }}
                    </div>
                </div>

                <div class="grid grid-cols-2 gap-4 mt-6">
                    <div class="border-2 border-black p-3">
                        <div class="text-xs text-gray-500">3. Total number of forms</div>
                        <div class="text-2xl font-bold text-center">{{ $total_forms }}</div>
                    </div>
                    <div class="border-2 border-black p-3">
                        <div class="text-xs text-gray-500">5. Total amount reported</div>
                        <div class="text-2xl font-bold text-center">${{ number_format($total_amount, 2) }}</div>
                    </div>
                </div>

                <div class="mt-4 p-3 bg-gray-50">
                    <div class="text-xs text-gray-500 mb-1">Check type of form being transmitted:</div>
                    <div class="flex items-center gap-2">
                        <div class="w-4 h-4 border border-black flex items-center justify-center text-xs font-bold">X</div>
                        <span>1099-NEC</span>
                    </div>
                </div>
            </div>

            <div class="mt-6 pt-4 border-t border-gray-300 text-xs text-gray-500 text-center">
                This form is a transmittal cover sheet — file with Copy A of all 1099-NEC forms.
            </div>
        </div>

        <div class="text-xs text-gray-400 mt-8 text-center">
            Generated by Zao Dash Tax Office — {{ now()->format('F j, Y g:i A') }}
        </div>
    </div>
</body>
</html>
