{{-- Oregon Form OR-40-V — Estimated Payment Voucher --}}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <script src="https://cdn.tailwindcss.com"></script>
    <style>
        @page { size: letter; margin: 0; }
        body { font-family: 'Courier New', monospace; }
    </style>
</head>
<body class="bg-white">
    {{-- Cover Letter / Instructions --}}
    <div class="p-12">
        <div class="border-b-2 border-green-700 pb-4 mb-8">
            <h1 class="text-2xl font-bold text-gray-900">Oregon Estimated Tax Payment — Q{{ $quarter }} {{ $year }}</h1>
            <p class="text-gray-600 mt-1">Prepared for {{ $profile->spouse_name ? $profile->spouse_name.' & ' : '' }}{{ $profile->user->name ?? 'Taxpayer' }}</p>
        </div>

        <div class="bg-green-50 border border-green-200 rounded-lg p-6 mb-8">
            <div class="text-center">
                <div class="text-sm text-green-700 font-semibold uppercase tracking-wide">Oregon Amount Due</div>
                <div class="text-4xl font-bold text-green-800 mt-1">${{ number_format($payment_amount, 2) }}</div>
                <div class="text-sm text-green-700 mt-2">Due by {{ $due_date }}</div>
            </div>
        </div>

        <h2 class="text-lg font-bold text-gray-800 mb-4">How to Pay</h2>

        {{-- Option 1: Oregon Revenue Online --}}
        <div class="mb-6">
            <h3 class="font-bold text-gray-700 mb-2">Option 1: Oregon Revenue Online (Recommended)</h3>
            <div class="bg-gray-50 rounded-lg p-4">
                <p class="text-sm text-gray-600 mb-2">{{ $payment_instructions['online']['url'] }}</p>
                <ol class="list-decimal list-inside text-sm text-gray-700 space-y-1">
                    @foreach($payment_instructions['online']['steps'] as $step)
                        <li>{{ $step }}</li>
                    @endforeach
                </ol>
            </div>
        </div>

        {{-- Option 2: Mail --}}
        <div class="mb-6">
            <h3 class="font-bold text-gray-700 mb-2">Option 2: Mail with Voucher Below</h3>
            <div class="bg-gray-50 rounded-lg p-4">
                <p class="text-sm text-gray-700">{{ $payment_instructions['mail']['note'] }}</p>
                <p class="text-sm text-gray-600 mt-2 whitespace-pre-line">{{ $payment_instructions['mail']['address'] }}</p>
            </div>
        </div>

        <div class="text-xs text-gray-400 mt-8 border-t pt-4">
            Generated by Zao Dash Tax Office — {{ now()->format('F j, Y g:i A') }}
        </div>
    </div>

    {{-- Payment Voucher --}}
    <div class="break-before-page p-12">
        <div class="border-2 border-black p-8 max-w-xl mx-auto" style="font-family: 'Courier New', monospace;">
            <div class="text-center border-b border-black pb-2 mb-4">
                <div class="text-xs">Oregon</div>
                <div class="text-2xl font-bold">OR-40-V</div>
                <div class="text-xs">Oregon Department of Revenue</div>
                <div class="text-xs mt-1">{{ $year }} Oregon Individual Income Tax Payment Voucher</div>
                <div class="text-xs">Quarter {{ $quarter }}</div>
            </div>

            <div class="text-xs space-y-3">
                <div>
                    <div class="text-xs text-gray-500">Name(s)</div>
                    <div class="font-bold text-sm border-b border-gray-300 py-1">
                        {{ strtoupper($profile->user->name ?? '') }}
                        @if($profile->spouse_name)
                            & {{ strtoupper($profile->spouse_name) }}
                        @endif
                    </div>
                </div>

                <div>
                    <div class="text-xs text-gray-500">Address</div>
                    <div class="border-b border-gray-300 py-1">
                        {{ strtoupper(($profile->address ?? '').', '.($profile->city ?? '').' '.($profile->state ?? '').' '.($profile->zip ?? '')) }}
                    </div>
                </div>

                <div class="flex justify-between items-center border-2 border-black p-3 bg-gray-50">
                    <div class="text-xs text-gray-500">Payment amount</div>
                    <div class="text-xl font-bold">${{ number_format($payment_amount, 2) }}</div>
                </div>

                <div class="text-xs text-gray-500 mt-2">
                    Mail to: Oregon Department of Revenue, PO Box 14950, Salem, OR 97309-0950
                </div>
            </div>
        </div>

        <div class="text-center mt-4 text-xs text-gray-400">
            ✂ Cut along dotted line — Mail voucher with payment
        </div>
    </div>
</body>
</html>
