<?php

use App\Models\SeoKeyword;
use App\Models\SeoPage;
use App\Models\SeoPerformanceHistory;

test('calculates conversion rate correctly', function () {
    $page = SeoPage::factory()->create([
        'clicks_30d' => 100,
        'total_leads' => 2,
    ]);

    // Conversion rate should be: (2 leads / 100 clicks) * 100 = 2%
    expect($page->conversion_rate)->toBe(2.0);
});

test('identifies underperforming pages', function () {
    $underperforming = SeoPage::factory()->create([
        'clicks_30d' => 60,
        'total_leads' => 0,
    ]);

    $performing = SeoPage::factory()->create([
        'clicks_30d' => 60,
        'total_leads' => 3,
    ]);

    expect($underperforming->isUnderperforming())->toBeTrue();
    expect($performing->isUnderperforming())->toBeFalse();
});

test('identifies pages needing meta optimization', function () {
    $needsOptimization = SeoPage::factory()->create([
        'avg_position_30d' => 4.5,
        'ctr_30d' => 1.5,
    ]);

    $doesNotNeed = SeoPage::factory()->create([
        'avg_position_30d' => 4.5,
        'ctr_30d' => 3.0,
    ]);

    expect($needsOptimization->needsMetaOptimization())->toBeTrue();
    expect($doesNotNeed->needsMetaOptimization())->toBeFalse();
});

test('has keywords relationship', function () {
    $page = SeoPage::factory()->create();
    SeoKeyword::factory()->count(3)->create(['seo_page_id' => $page->id]);

    expect($page->keywords)->toHaveCount(3);
});

test('has performance history relationship', function () {
    $page = SeoPage::factory()->create();
    SeoPerformanceHistory::factory()->count(5)->create(['seo_page_id' => $page->id]);

    expect($page->performanceHistory)->toHaveCount(5);
});

test('active scope filters active pages only', function () {
    SeoPage::factory()->create(['status' => 'active']);
    SeoPage::factory()->create(['status' => 'active']);
    SeoPage::factory()->create(['status' => 'draft']);

    expect(SeoPage::active()->count())->toBe(2);
});

test('generated by agent scope filters correctly', function () {
    SeoPage::factory()->create(['generated_by_agent' => true]);
    SeoPage::factory()->create(['generated_by_agent' => true]);
    SeoPage::factory()->create(['generated_by_agent' => false]);

    expect(SeoPage::generatedByAgent()->count())->toBe(2);
});

test('high performing scope returns pages with conversion rate above 1', function () {
    SeoPage::factory()->create(['conversion_rate' => 2.5, 'total_revenue' => 10000]);
    SeoPage::factory()->create(['conversion_rate' => 1.2, 'total_revenue' => 5000]);
    SeoPage::factory()->create(['conversion_rate' => 0.5, 'total_revenue' => 2000]);

    $highPerformers = SeoPage::highPerforming()->get();

    expect($highPerformers)->toHaveCount(2);
    expect($highPerformers->first()->conversion_rate)->toBeGreaterThan(1.0);
});
