<?php

namespace App\Jobs;

use App\Enums\SeoPageStatus;
use App\Models\SeoPage;
use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Foundation\Bus\Dispatchable;
use Illuminate\Queue\InteractsWithQueue;
use Illuminate\Queue\SerializesModels;
use Illuminate\Support\Facades\Log;

/**
 * Generate a single SEO content piece based on orchestrator strategy.
 *
 * This job is dispatched by the Programmatic SEO Orchestrator
 * and handles generation of ONE piece of content using the specified playbook.
 */
class GenerateSeoContentJob implements ShouldQueue
{
    use Dispatchable, InteractsWithQueue, Queueable, SerializesModels;

    /**
     * Number of times the job may be attempted.
     */
    public int $tries = 2;

    /**
     * Seconds to wait before retrying.
     */
    public array $backoff = [60, 300];

    /**
     * Maximum seconds the job can run (15 minutes per piece).
     */
    public int $timeout = 900;

    /**
     * Create a new job instance.
     */
    public function __construct(
        public string $title,
        public string $keyword,
        public string $playbook,
        public string $urlSlug,
        public array $proprietaryData,
        public int $priority = 5,
        public ?int $orchestratorRunId = null
    ) {}

    /**
     * Execute the job.
     */
    public function handle(): void
    {
        Log::info('Starting SEO content generation', [
            'title' => $this->title,
            'playbook' => $this->playbook,
            'keyword' => $this->keyword,
        ]);

        try {
            // Check if page already exists
            $existingPage = SeoPage::where('page_url', '/'.$this->urlSlug)->first();

            if ($existingPage) {
                // Skip if page is already published or actively being generated
                if (in_array($existingPage->status, [SeoPageStatus::Published, SeoPageStatus::Generating])) {
                    Log::info('SEO page already exists, skipping generation', [
                        'page_id' => $existingPage->id,
                        'url' => $existingPage->page_url,
                        'status' => $existingPage->status->value,
                    ]);

                    return;
                }

                // Reset failed/draft pages for regeneration
                $existingPage->update([
                    'status' => SeoPageStatus::Generating,
                    'orchestrator_run_id' => $this->orchestratorRunId,
                ]);

                $page = $existingPage;

                Log::info('Retrying SEO page generation', [
                    'page_id' => $page->id,
                    'url' => $page->page_url,
                ]);
            } else {
                // Create new draft page record
                $page = SeoPage::create([
                    'page_url' => '/'.$this->urlSlug,
                    'target_keyword' => $this->keyword,
                    'page_type' => $this->mapPlaybookToPageType($this->playbook),
                    'meta_title' => $this->title,
                    'meta_description' => "Learn about {$this->keyword}. Generated by programmatic SEO.",
                    'generated_by_agent' => true,
                    'orchestrator_run_id' => $this->orchestratorRunId,
                    'status' => SeoPageStatus::Generating,
                    'total_leads' => 0,
                    'total_projects' => 0,
                    'total_revenue' => 0,
                    'optimization_count' => 0,
                ]);

                Log::info('Created draft SEO page', [
                    'page_id' => $page->id,
                    'url' => $page->page_url,
                ]);
            }

            // Generate content using SEO Content Writer agent
            $contentAgent = \App\Models\Agent::where('slug', 'seo-content-writer')->first();

            if (! $contentAgent || $contentAgent->status !== 'active') {
                Log::warning('SEO Content Writer agent not available, skipping content generation', [
                    'page_id' => $page->id,
                ]);

                $page->update(['status' => SeoPageStatus::Draft]);

                return;
            }

            // Create agent run for content generation
            $run = $contentAgent->runs()->create([
                'session_id' => \Illuminate\Support\Str::uuid(),
                'status' => 'running',
                'task' => "Generate {$this->playbook} content for '{$this->title}'",
                'context' => [
                    'seo_page_id' => $page->id,
                    'title' => $this->title,
                    'keyword' => $this->keyword,
                    'playbook' => $this->playbook,
                    'url_slug' => $this->urlSlug,
                    'proprietary_data' => $this->proprietaryData,
                    'orchestrator_run_id' => $this->orchestratorRunId,
                    'timeout_seconds' => 600, // 10 minutes per content piece
                ],
                'invocation_source' => \App\Models\AgentRun::SOURCE_SCHEDULED,
                'invoked_by' => 'GenerateSeoContentJob',
                'started_at' => now(),
            ]);

            // Dispatch the content generation agent
            \App\Jobs\RunAgentJob::dispatch($run);

            Log::info('SEO content generation agent dispatched', [
                'page_id' => $page->id,
                'agent_run_id' => $run->id,
            ]);

        } catch (\Throwable $e) {
            Log::error('SEO content generation failed', [
                'title' => $this->title,
                'error' => $e->getMessage(),
            ]);

            throw $e;
        }
    }

    /**
     * Map playbook to page_type enum value.
     */
    protected function mapPlaybookToPageType(string $playbook): string
    {
        return match ($playbook) {
            'Templates', 'Tools' => 'template',
            'Curation', 'Rankings' => 'curation',
            'Converters', 'Calculators' => 'tool',
            'Comparisons' => 'comparison',
            'Examples', 'Galleries' => 'gallery',
            'Location' => 'location',
            'Persona', 'Vertical' => 'service',
            'Integration' => 'integration',
            'Glossary', 'Educational' => 'guide',
            'Directory', 'Listings' => 'directory',
            'Case Study', 'Profile' => 'case-study',
            default => 'landing',
        };
    }

    /**
     * Job tags for Horizon.
     */
    public function tags(): array
    {
        return [
            'seo-content',
            'playbook:'.$this->playbook,
            'priority:'.$this->priority,
        ];
    }
}
